# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MCXXglxy1H3_1eTxV-BUC9UQnezA6G8U
"""

# ==========================================
# app.py (AskMyPDF Branded AI Voice PDF Chatbot)
# ==========================================

import streamlit as st
from PyPDF2 import PdfReader
from langchain.text_splitter import RecursiveCharacterTextSplitter
from langchain_community.vectorstores import FAISS
from langchain_openai import OpenAIEmbeddings, ChatOpenAI
from langchain.chains import ConversationalRetrievalChain
from openai import OpenAI
import os
import tempfile

# =========================
# 🔧 BRAND CONFIG (AskMyPDF)
# =========================
APP_NAME = "AskMyPDF"
TAGLINE = "Smart PDF Chatbot with Voice AI"
PRIMARY_COLOR = "#22c55e"   # green
SECONDARY_COLOR = "#0f172a" # dark
LOGO_URL = "/mnt/data/a_digital_vector_logo_design_for_askmypdf_featur.png"  # your generated logo
FOOTER_TEXT = "Built by Noorani 🚀"

# =========================
# Page Config
# ==========================
st.set_page_config(page_title=APP_NAME, page_icon="🤖", layout="wide")

# =========================
# Custom CSS (Brand Theme)
# ==========================
st.markdown(f"""
<style>
body {{background-color: {SECONDARY_COLOR};}}

h1 {{color: white; text-align:center;}}

.header {{
    display:flex;
    align-items:center;
    justify-content:center;
    gap:15px;
}}

.header img {{width:60px;}}

.tagline {{text-align:center; color:gray; margin-bottom:20px;}}

.stChatMessage[data-testid="user"] {{background-color:#1e293b; border-radius:12px;}}
.stChatMessage[data-testid="assistant"] {{background-color:#020617; border-radius:12px;}}

button[kind="primary"] {{background-color:{PRIMARY_COLOR};}}
</style>
""", unsafe_allow_html=True)

# =========================
# Header UI
# ==========================
st.markdown(f"""
<div class='header'>
    <img src='{LOGO_URL}'>
    <h1>{APP_NAME}</h1>
</div>
<p class='tagline'>{TAGLINE}</p>
""", unsafe_allow_html=True)

# =========================
# Sidebar
# ==========================
st.sidebar.markdown(f"## ⚙️ {APP_NAME}")
api_key = st.sidebar.text_input("🔑 OpenAI API Key", type="password")

client = None
if api_key:
    os.environ["OPENAI_API_KEY"] = api_key
    client = OpenAI(api_key=api_key)

pdfs = st.sidebar.file_uploader("📄 Upload PDFs", type="pdf", accept_multiple_files=True)

# =========================
# Session State
# ==========================
if "chat_history" not in st.session_state:
    st.session_state.chat_history = []

if "vectorstore" not in st.session_state:
    st.session_state.vectorstore = None

# =========================
# Process PDFs
# ==========================
@st.cache_resource
def process_pdfs(pdfs):
    text = ""
    for pdf in pdfs:
        reader = PdfReader(pdf)
        for page in reader.pages:
            content = page.extract_text()
            if content:
                text += content

    splitter = RecursiveCharacterTextSplitter(chunk_size=1000, chunk_overlap=200)
    chunks = splitter.split_text(text)

    embeddings = OpenAIEmbeddings()
    return FAISS.from_texts(chunks, embeddings)

if pdfs and api_key:
    with st.spinner("⚡ Processing PDFs..."):
        st.session_state.vectorstore = process_pdfs(pdfs)
    st.success("✅ Ready to chat!")

# =========================
# Voice Functions
# ==========================
def transcribe_audio(audio_file):
    with open(audio_file, "rb") as f:
        transcript = client.audio.transcriptions.create(
            model="gpt-4o-mini-transcribe",
            file=f
        )
    return transcript.text


def speak_text(text):
    response = client.audio.speech.create(
        model="gpt-4o-mini-tts",
        voice="alloy",
        input=text
    )

    with tempfile.NamedTemporaryFile(delete=False, suffix=".mp3") as tmp:
        tmp.write(response.content)
        return tmp.name

# =========================
# Chat
# ==========================
if st.session_state.vectorstore and client:

    llm = ChatOpenAI(model="gpt-4o-mini", temperature=0)

    qa_chain = ConversationalRetrievalChain.from_llm(
        llm,
        retriever=st.session_state.vectorstore.as_retriever()
    )

    st.subheader("💬 Ask or Upload Voice")

    user_input = st.chat_input("Type your question...")

    audio_file = st.file_uploader("🎤 Upload voice (mp3/wav)", type=["mp3", "wav"])

    if audio_file:
        with tempfile.NamedTemporaryFile(delete=False) as tmp:
            tmp.write(audio_file.read())
            user_input = transcribe_audio(tmp.name)
            st.info(f"You said: {user_input}")

    if user_input:
        result = qa_chain.invoke({
            "question": user_input,
            "chat_history": st.session_state.chat_history
        })

        answer = result["answer"]
        st.session_state.chat_history.append((user_input, answer))

        audio_path = speak_text(answer)
        st.audio(audio_path)

    for q, a in st.session_state.chat_history:
        with st.chat_message("user", avatar="🧑"):
            st.write(q)
        with st.chat_message("assistant", avatar="🤖"):
            st.write(a)

else:
    st.info("Upload PDFs and enter API key to start")

# =========================
# Footer
# ==========================
st.markdown("---")
st.markdown(f"<p style='text-align:center; color:gray;'>{FOOTER_TEXT}</p>", unsafe_allow_html=True)

# ==========================================
# requirements.txt
# ==========================================

"""
streamlit
PyPDF2
langchain
langchain-community
langchain-openai
faiss-cpu
openai
"""